[workspace]
members = [
  "crates/auction-block-listener",
  "crates/auction-cli",
  "crates/auction-interface",
]
resolver = "2"

[workspace.package]
version = "0.0.1"
edition = "2021"
authors = ["lilyjjo"]
license = "MIT OR Apache-2.0"
exclude = ["benches/", "tests/"]

[workspace.dependencies]
