[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
  '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
  '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
  '@uniswap/v3-core/contracts/=lib/v3-core/contracts'
]